server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Redirects non-file URLs back to index.html
    }

    # Proxy /api-sarvam requests to Sarvam AI server to prevent CORS and 404 errors in production
    location /api-sarvam/ {
        proxy_pass https://api.sarvam.ai/;
        proxy_set_header Host api.sarvam.ai;
        proxy_ssl_server_name on;
        proxy_ssl_protocols TLSv1.2 TLSv1.3;
    }
}
